name: hello-class
on: push
jobs: 
  my-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: my-step
        run: echo "hello world"
  another-job:
    runs-on: ubuntu-latest
    steps:
      - name: new-step
        run: echo "experimenting"